title: Prithwish Ghosh
#logo
description: Statistician/Astro-Statistician
description: I am currently a first-year PhD student at the Department of Statistics at North Carolina State University. 
Currently, I am engaged in Several projects on the following topics like, circular data analysis, Bayesian Inference applied to Environmental, Astronomical data, and other interdisciplinary subjects. 
theme: jekyll-theme-minimal
